use lsearch

CREATE TABLE IF NOT EXISTS "users" (
    "id" INTEGER AUTO_INCREMENT PRIMARY KEY,
    "providerId" VARCHAR(100) NOT NULL,
    "name" VARCHAR(50) NULL,
    "email" VARCHAR(50) NULL,
    "role" VARCHAR(50) NOT NULL,

    "createdAt" TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY ("id")
);
